services:
  # Postgres for auth/users
  db:
    image: postgres:17.0
    hostname: localhost

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=math_course
    volumes:
      - pgdata:/var/lib/postgresql/data

  # MongoDB for Payload CMS
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo_data:/data/db
    logging:
      driver: none

volumes:
  pgdata:
  mongo_data:
